# Checkov
version: 0.1
phases:
  pre_build:
    commands:
      - echo pre_build starting

  build:
    commands:
      - echo build starting
      - echo starting checkov
      - ls
      - checkov -d . || true #using || true to let bypass failed checks but preserve output
      - echo saving checkov output
      - checkov -s -d . > checkov.result.txt || true